"""add pass secure

Revision ID: 14640b7b2d0d
Revises: 82d496de3afb
Create Date: 2020-12-16 13:37:55.859554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14640b7b2d0d'
down_revision = '82d496de3afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
